version: '1'
services:
  distribution-db-test:
    extends:
      service: books-db
      file: compose.yaml
    ports:
      - '15433:5432'
    volumes:
      - ./db-data-local:/var/lib/postgresql/data