server:
  port: 9092

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/books"
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
logging:
  level:
    org:
      springframework: DEBUG
    org.springframework.boot: DEBUG