server:
  port: 9092

spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/books"
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/master.xml
    default-schema: public

logging:
  level:
    liquibase: DEBUG

aws:
  region: ${STORE_REGION}
  s3:
    bucket: ${STORE_BUCKET_NAME}
    access-key: ${STORE_ACCESS_KEY}
    secret-key: ${STORE_SECRET_KEY}