spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/books
    username: test
    password: test
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: false
