--liquibase formatted sql
--changeset maxim:my-book-table

CREATE TABLE "user"
(
    id BIGINT PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    username   VARCHAR(50)  NOT NULL UNIQUE,
    email      VARCHAR(100) NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    password   VARCHAR(100) NOT NULL,
    enabled    BOOLEAN      NOT NULL
);
INSERT INTO "user" (username, email, password, enabled)
VALUES ('alpha_admin', 'alpha.admin@example.com', 'password_1', TRUE),
       ('beta_user', 'beta.user@example.com', 'password_2', TRUE),
       ('gamma_seller', 'gamma.seller@example.com', 'password_3', TRUE),
       ('delta_member', 'delta.member@example.com', 'password_4', FALSE),
       ('epsilon_user', 'epsilon.user@example.com', 'password_5', TRUE),
       ('zeta_trader', 'zeta.trader@example.com', 'password_6', TRUE),
       ('eta_manager', 'eta.manager@example.com', 'password_7', FALSE),
       ('theta_member', 'theta.member@example.com', 'password_8', TRUE),
       ('iota_vendor', 'iota.vendor@example.com', 'password_9', TRUE),
       ('kappa_user', 'kappa.user@example.com', 'password_10', FALSE);

CREATE TABLE roles
(
    id SMALLINT PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 32767 CACHE 1 ),
    name VARCHAR(50) NOT NULL UNIQUE
);

INSERT INTO roles (name)
VALUES ('ADMIN'),
       ('USER'),
       ('SELLER');
CREATE TABLE user_roles
(
    user_id INT REFERENCES "user" (id) ON DELETE CASCADE,
    role_id INT REFERENCES roles (id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, role_id)
);

INSERT INTO user_roles (user_id, role_id)
VALUES (1, (SELECT id FROM roles WHERE name = 'ADMIN')),
       (1, (SELECT id FROM roles WHERE name = 'USER')),
       (1, (SELECT id FROM roles WHERE name = 'SELLER')),
       (2, (SELECT id FROM roles WHERE name = 'USER')),
       (2, (SELECT id FROM roles WHERE name = 'ADMIN')),
       (3, (SELECT id FROM roles WHERE name = 'USER')),
       (3, (SELECT id FROM roles WHERE name = 'SELLER')),
       (4, (SELECT id FROM roles WHERE name = 'USER')),
       (5, (SELECT id FROM roles WHERE name = 'USER')),
       (6, (SELECT id FROM roles WHERE name = 'SELLER')),
       (6, (SELECT id FROM roles WHERE name = 'USER')),
       (7, (SELECT id FROM roles WHERE name = 'ADMIN')),
       (8, (SELECT id FROM roles WHERE name = 'USER')),
       (9, (SELECT id FROM roles WHERE name = 'SELLER')),
       (10, (SELECT id FROM roles WHERE name = 'USER'));

CREATE TABLE categories
(
    id SMALLINT PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 32767 CACHE 1 ),
    name        VARCHAR(100) NOT NULL UNIQUE,
    description TEXT
);
CREATE TABLE product
(
    id BIGINT PRIMARY KEY NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name           VARCHAR(100)   NOT NULL,
    description    TEXT,
    price          DECIMAL(10, 2) NOT NULL,
    stock_quantity INTEGER       DEFAULT 0,
    sku            VARCHAR(50) UNIQUE,
    image_url      TEXT,
    brand          VARCHAR(100),
    rating         DECIMAL(2, 1) DEFAULT 0.0,
    is_active      BOOLEAN       DEFAULT TRUE,
    category_id    INTEGER        REFERENCES categories (id) ON DELETE SET NULL,
    created_at     TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP     DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE comment
(
    id             SERIAL PRIMARY KEY,
    user_id        INTEGER REFERENCES "user" (id) ON DELETE CASCADE,
    product_id     INTEGER REFERENCES product (id) ON DELETE CASCADE,
    content        TEXT           NOT NULL,
    rating         DECIMAL(2, 1) DEFAULT 0.0,
    title          VARCHAR(255),
    is_recommended BOOLEAN       DEFAULT TRUE,
    created_at     TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP     DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO categories (name, description)
VALUES ('Electronics', 'Devices and gadgets including computers, phones, and accessories.'),
       ('Books', 'A wide range of books from various genres.'),
       ('Home Goods', 'Products for home decor, kitchen, and living.'),
       ('Apparel', 'Clothing, footwear, and fashion accessories.'),
       ('Sports & Outdoors', 'Equipment and gear for sports and outdoor activities.');

-- Generate 100 Products
INSERT INTO product (name, description, price, stock_quantity, sku, image_url, brand, rating, is_active, category_id)
VALUES ('Laptop Pro X1', 'Powerful laptop for professionals.', 1200.00, 50, 'LAPX1-001',
        'http://example.com/laptopx1.jpg', 'TechBrand', 4.7, TRUE,
        (SELECT id FROM categories WHERE name = 'Electronics')),
       ('Wireless Headphones Z2', 'Noise-cancelling over-ear headphones.', 150.00, 120, 'HEADZ2-002',
        'http://example.com/headz2.jpg', 'AudioMax', 4.5, TRUE, (SELECT id FROM categories WHERE name = 'Electronics')),
       ('Smartphone Elite 10', 'Flagship smartphone with advanced camera.', 900.00, 80, 'PHONE-E10-003',
        'http://example.com/phonee10.jpg', 'MobileTech', 4.8, TRUE,
        (SELECT id FROM categories WHERE name = 'Electronics')),
       ('Mechanical Keyboard G5', 'Gaming keyboard with RGB backlighting.', 80.00, 200, 'KEYBG5-004',
        'http://example.com/keybg5.jpg', 'GamerGear', 4.6, TRUE,
        (SELECT id FROM categories WHERE name = 'Electronics')),
       ('Smartwatch S3', 'Fitness tracker and smartwatch with heart rate monitor.', 250.00, 90, 'SMARTW-S3-005',
        'http://example.com/smartws3.jpg', 'WearableCo', 4.3, TRUE,
        (SELECT id FROM categories WHERE name = 'Electronics')),
       ('E-Reader PaperView', 'Lightweight e-reader with glare-free screen.', 100.00, 150, 'EREADER-006',
        'http://example.com/ereader.jpg', 'BookNook', 4.7, TRUE,
        (SELECT id FROM categories WHERE name = 'Electronics')),
       ('4K UHD Monitor 27"', '27-inch monitor with stunning 4K resolution.', 350.00, 60, 'MONITOR-27-007',
        'http://example.com/monitor27.jpg', 'ViewTech', 4.6, TRUE,
        (SELECT id FROM categories WHERE name = 'Electronics')),
       ('Portable Bluetooth Speaker', 'Compact speaker with powerful sound.', 60.00, 300, 'BT-SPEAKER-008',
        'http://example.com/btspeaker.jpg', 'SoundFlow', 4.2, TRUE,
        (SELECT id FROM categories WHERE name = 'Electronics')),
       ('External SSD 1TB', 'High-speed external solid state drive.', 120.00, 180, 'SSD-1TB-009',
        'http://example.com/ssd1tb.jpg', 'DataSafe', 4.8, TRUE, (SELECT id FROM categories WHERE name = 'Electronics')),
       ('Gaming Mouse M9', 'Precision gaming mouse with customizable buttons.', 45.00, 250, 'GMOUSE-M9-010',
        'http://example.com/gmousem9.jpg', 'GamerGear', 4.5, TRUE,
        (SELECT id FROM categories WHERE name = 'Electronics')),
       ('The Alchemist', 'A philosophical novel by Paulo Coelho.', 15.99, 500, 'BOOK-ALCH-011',
        'http://example.com/alchemist.jpg', 'HarperCollins', 4.9, TRUE,
        (SELECT id FROM categories WHERE name = 'Books')),
       ('Sapiens: A Brief History of Humankind', 'Non-fiction book by Yuval Noah Harari.', 20.50, 400, 'BOOK-SAP-012',
        'http://example.com/sapiens.jpg', 'Penguin Random House', 4.8, TRUE,
        (SELECT id FROM categories WHERE name = 'Books')),
       ('1984', 'Dystopian social science fiction novel by George Orwell.', 12.00, 600, 'BOOK-1984-013',
        'http://example.com/1984.jpg', 'Signet Classic', 4.7, TRUE, (SELECT id FROM categories WHERE name = 'Books')),
       ('To Kill a Mockingbird', 'Classic novel by Harper Lee.', 10.99, 550, 'BOOK-TKAM-014',
        'http://example.com/tkam.jpg', 'Grand Central Publishing', 4.9, TRUE,
        (SELECT id FROM categories WHERE name = 'Books')),
       ('The Great Gatsby', 'A novel by F. Scott Fitzgerald.', 9.50, 700, 'BOOK-TGG-015',
        'http://example.com/gatsby.jpg', 'Scribner', 4.6, TRUE, (SELECT id FROM categories WHERE name = 'Books')),
       ('Becoming', 'Memoir by Michelle Obama.', 18.00, 450, 'BOOK-BECOM-016', 'http://example.com/becoming.jpg',
        'Crown', 4.7, TRUE, (SELECT id FROM categories WHERE name = 'Books')),
       ('Educated', 'A memoir by Tara Westover.', 16.50, 380, 'BOOK-EDUC-017', 'http://example.com/educated.jpg',
        'Random House', 4.8, TRUE, (SELECT id FROM categories WHERE name = 'Books')),
       ('The Lord of the Rings', 'Epic high-fantasy novel by J.R.R. Tolkien.', 25.00, 300, 'BOOK-LOTR-018',
        'http://example.com/lotr.jpg', 'Houghton Mifflin Harcourt', 4.9, TRUE,
        (SELECT id FROM categories WHERE name = 'Books')),
       ('Cosmos', 'A non-fiction book by Carl Sagan.', 14.00, 420, 'BOOK-COSMOS-019', 'http://example.com/cosmos.jpg',
        'Random House', 4.7, TRUE, (SELECT id FROM categories WHERE name = 'Books')),
       ('Pride and Prejudice', 'Romantic novel by Jane Austen.', 11.25, 650, 'BOOK-PAP-020',
        'http://example.com/pandp.jpg', 'Penguin Classics', 4.8, TRUE,
        (SELECT id FROM categories WHERE name = 'Books')),
       ('Coffee Maker Deluxe', 'Programmable coffee maker with grinder.', 75.00, 100, 'HOME-CM-021',
        'http://example.com/coffeemaker.jpg', 'KitchenMaster', 4.4, TRUE,
        (SELECT id FROM categories WHERE name = 'Home Goods')),
       ('Air Fryer XL', 'Large capacity air fryer for healthy cooking.', 99.00, 80, 'HOME-AF-022',
        'http://example.com/airfryer.jpg', 'CookSmart', 4.6, TRUE,
        (SELECT id FROM categories WHERE name = 'Home Goods')),
       ('Robot Vacuum Cleaner', 'Smart vacuum cleaner with app control.', 250.00, 50, 'HOME-RV-023',
        'http://example.com/robotvac.jpg', 'CleanBot', 4.5, TRUE,
        (SELECT id FROM categories WHERE name = 'Home Goods')),
       ('Luxury Bedding Set', 'King size bedding set with Egyptian cotton.', 180.00, 70, 'HOME-BED-024',
        'http://example.com/beddingset.jpg', 'DreamComfort', 4.7, TRUE,
        (SELECT id FROM categories WHERE name = 'Home Goods')),
       ('Smart LED Light Bulbs (4-pack)', 'App-controlled color-changing LED bulbs.', 40.00, 150, 'HOME-LED-025',
        'http://example.com/ledbulbs.jpg', 'BrilliantHome', 4.3, TRUE,
        (SELECT id FROM categories WHERE name = 'Home Goods')),
       ('Non-Stick Cookware Set', '10-piece non-stick pot and pan set.', 120.00, 60, 'HOME-COOK-026',
        'http://example.com/cookwareset.jpg', 'ChefEssentials', 4.6, TRUE,
        (SELECT id FROM categories WHERE name = 'Home Goods')),
       ('Aromatherapy Diffuser', 'Ultrasonic essential oil diffuser with LED.', 30.00, 200, 'HOME-DIFF-027',
        'http://example.com/diffuser.jpg', 'ZenHome', 4.2, TRUE, (SELECT id FROM categories WHERE name = 'Home Goods')),
       ('Ergonomic Office Chair', 'Adjustable office chair with lumbar support.', 190.00, 40, 'HOME-CHAIR-028',
        'http://example.com/officechair.jpg', 'WorkSmart', 4.8, TRUE,
        (SELECT id FROM categories WHERE name = 'Home Goods')),
       ('Digital Kitchen Scale', 'Precision kitchen scale with LCD display.', 25.00, 250, 'HOME-SCALE-029',
        'http://example.com/kitchenscale.jpg', 'BakeRight', 4.1, TRUE,
        (SELECT id FROM categories WHERE name = 'Home Goods')),
       ('Memory Foam Pillow', 'Contour memory foam pillow for neck support.', 35.00, 180, 'HOME-PILL-030',
        'http://example.com/pillow.jpg', 'SleepWell', 4.5, TRUE, (SELECT id FROM categories WHERE name = 'Home Goods')),
       ('Men''s Classic T-Shirt', '100% cotton crew neck t-shirt.', 20.00, 500, 'APP-TSHIRT-031',
        'http://example.com/mentshirt.jpg', 'EverydayWear', 4.5, TRUE,
        (SELECT id FROM categories WHERE name = 'Apparel')),
       ('Women''s Yoga Leggings', 'High-waisted, stretchable yoga leggings.', 35.00, 450, 'APP-YOGA-032',
        'http://example.com/yogaleggings.jpg', 'ActiveFit', 4.7, TRUE,
        (SELECT id FROM categories WHERE name = 'Apparel')),
       ('Unisex Hoodie', 'Soft fleece hoodie with kangaroo pocket.', 45.00, 300, 'APP-HOODIE-033',
        'http://example.com/hoodie.jpg', 'ComfortZone', 4.6, TRUE, (SELECT id FROM categories WHERE name = 'Apparel')),
       ('Running Shoes (Men''s)', 'Lightweight and breathable running shoes.', 80.00, 200, 'APP-RUNM-034',
        'http://example.com/runshoesmen.jpg', 'StrideSport', 4.4, TRUE,
        (SELECT id FROM categories WHERE name = 'Apparel')),
       ('Running Shoes (Women''s)', 'Cushioned running shoes for optimal comfort.', 80.00, 200, 'APP-RUNW-035',
        'http://example.com/runshoeswomen.jpg', 'StrideSport', 4.5, TRUE,
        (SELECT id FROM categories WHERE name = 'Apparel')),
       ('Denim Jeans (Slim Fit)', 'Classic slim fit denim jeans.', 60.00, 250, 'APP-JEANS-036',
        'http://example.com/slimjeans.jpg', 'BlueDenim', 4.3, TRUE, (SELECT id FROM categories WHERE name = 'Apparel')),
       ('Summer Dress (Floral)', 'Light and airy floral print summer dress.', 50.00, 180, 'APP-DRESS-037',
        'http://example.com/summerdress.jpg', 'FashionBloom', 4.6, TRUE,
        (SELECT id FROM categories WHERE name = 'Apparel')),
       ('Leather Wallet', 'Genuine leather wallet with multiple card slots.', 40.00, 350, 'APP-WALLET-038',
        'http://example.com/leatherwallet.jpg', 'ElegantCarry', 4.8, TRUE,
        (SELECT id FROM categories WHERE name = 'Apparel')),
       ('Sports Socks (3-pair)', 'Moisture-wicking athletic socks.', 15.00, 600, 'APP-SOCKS-039',
        'http://example.com/sportssocks.jpg', 'ActiveFoot', 4.2, TRUE,
        (SELECT id FROM categories WHERE name = 'Apparel')),
       ('Winter Jacket (Unisex)', 'Warm, waterproof winter jacket with hood.', 120.00, 100, 'APP-WJACKET-040',
        'http://example.com/winterjacket.jpg', 'ColdGear', 4.7, TRUE,
        (SELECT id FROM categories WHERE name = 'Apparel')),
       ('Yoga Mat Deluxe', 'Extra thick non-slip yoga mat.', 30.00, 150, 'SPORT-YMAT-041',
        'http://example.com/yogamat.jpg', 'FlexFit', 4.6, TRUE,
        (SELECT id FROM categories WHERE name = 'Sports & Outdoors')),
       ('Camping Tent (2-person)', 'Lightweight and easy-setup tent.', 90.00, 80, 'SPORT-TENT-042',
        'http://example.com/campingtent.jpg', 'WildernessPro', 4.5, TRUE,
        (SELECT id FROM categories WHERE name = 'Sports & Outdoors')),
       ('Hiking Backpack (50L)', 'Durable hiking backpack with ample storage.', 70.00, 100, 'SPORT-HBP-043',
        'http://example.com/hikingbackpack.jpg', 'TrailBlazer', 4.7, TRUE,
        (SELECT id FROM categories WHERE name = 'Sports & Outdoors')),
       ('Dumbbell Set (Adjustable)', 'Adjustable dumbbell set for home gym.', 150.00, 60, 'SPORT-DUMB-044',
        'http://example.com/dumbbellset.jpg', 'IronStrength', 4.8, TRUE,
        (SELECT id FROM categories WHERE name = 'Sports & Outdoors')),
       ('Water Bottle (Stainless Steel)', 'Insulated stainless steel water bottle.', 20.00, 300, 'SPORT-WB-045',
        'http://example.com/waterbottle.jpg', 'HydrateGo', 4.9, TRUE,
        (SELECT id FROM categories WHERE name = 'Sports & Outdoors')),
       ('Fitness Tracker Watch', 'Activity tracker with heart rate and sleep monitoring.', 60.00, 120, 'SPORT-FTW-046',
        'http://example.com/fitnesstracker.jpg', 'HealthSync', 4.4, TRUE,
        (SELECT id FROM categories WHERE name = 'Sports & Outdoors')),
       ('Bicycle Helmet', 'Lightweight and ventilated bicycle helmet.', 40.00, 180, 'SPORT-BH-047',
        'http://example.com/bikehelmet.jpg', 'RideSafe', 4.3, TRUE,
        (SELECT id FROM categories WHERE name = 'Sports & Outdoors')),
       ('Portable Camping Stove', 'Compact propane stove for outdoor cooking.', 45.00, 90, 'SPORT-CSTV-048',
        'http://example.com/campingstove.jpg', 'OutdoorChef', 4.6, TRUE,
        (SELECT id FROM categories WHERE name = 'Sports & Outdoors')),
       ('Resistance Bands Set', 'Set of 5 resistance bands with different strengths.', 25.00, 250, 'SPORT-RB-049',
        'http://example.com/resistancebands.jpg', 'ToneUp', 4.5, TRUE,
        (SELECT id FROM categories WHERE name = 'Sports & Outdoors')),
       ('Sleeping Bag (Compact)', 'Lightweight and warm sleeping bag.', 55.00, 130, 'SPORT-SB-050',
        'http://example.com/sleepingbag.jpg', 'CozyNights', 4.7, TRUE,
        (SELECT id FROM categories WHERE name = 'Sports & Outdoors')),
       ('Bluetooth Earbuds', 'True wireless earbuds with charging case.', 70.00, 200, 'EARBUDS-051',
        'http://example.com/earbuds.jpg', 'SoundBeats', 4.3, TRUE,
        (SELECT id FROM categories WHERE name = 'Electronics')),
       ('Drawing Tablet', 'Graphics tablet for digital art.', 110.00, 70, 'DRAW-TAB-052',
        'http://example.com/drawingtablet.jpg', 'ArtDigital', 4.6, TRUE,
        (SELECT id FROM categories WHERE name = 'Electronics')),
       ('Projector Mini', 'Portable mini projector for movies.', 180.00, 40, 'PROJ-MINI-053',
        'http://example.com/miniprojector.jpg', 'MovieTime', 4.2, TRUE,
        (SELECT id FROM categories WHERE name = 'Electronics')),
       ('Action Camera 4K', 'Waterproof action camera for adventures.', 200.00, 60, 'ACTIONCAM-054',
        'http://example.com/actioncam.jpg', 'GoCapture', 4.7, TRUE,
        (SELECT id FROM categories WHERE name = 'Electronics')),
       ('Smart Home Hub', 'Central hub for smart home devices.', 95.00, 55, 'SMARTH-HUB-055',
        'http://example.com/smarthub.jpg', 'ConnectHome', 4.4, TRUE,
        (SELECT id FROM categories WHERE name = 'Electronics')),
       ('Coding for Beginners', 'Introduction to programming for beginners.', 22.00, 300, 'BOOK-CODE-056',
        'http://example.com/codingbook.jpg', 'TechBooks', 4.5, TRUE, (SELECT id FROM categories WHERE name = 'Books')),
       ('The Art of Photography', 'Guide to photography techniques and concepts.', 28.00, 250, 'BOOK-PHOTO-057',
        'http://example.com/photobook.jpg', 'VisualArts', 4.6, TRUE, (SELECT id FROM categories WHERE name = 'Books')),
       ('Healthy Cooking Cookbook', 'Recipes for nutritious and delicious meals.', 17.50, 400, 'BOOK-COOK-058',
        'http://example.com/cookbook.jpg', 'TasteGood', 4.7, TRUE, (SELECT id FROM categories WHERE name = 'Books')),
       ('Gardening for Dummies', 'Beginner''s guide to gardening.', 14.00, 350, 'BOOK-GARDEN-059',
        'http://example.com/gardeningbook.jpg', 'HobbyGuides', 4.1, TRUE,
        (SELECT id FROM categories WHERE name = 'Books')),
       ('Self-Improvement Handbook', 'Tips and strategies for personal growth.', 19.00, 420, 'BOOK-SELF-060',
        'http://example.com/selfimpbook.jpg', 'MindGrowth', 4.8, TRUE,
        (SELECT id FROM categories WHERE name = 'Books')),
       ('Blender High-Speed', 'Powerful blender for smoothies and shakes.', 85.00, 90, 'HOME-BLEND-061',
        'http://example.com/blender.jpg', 'PowerBlend', 4.6, TRUE,
        (SELECT id FROM categories WHERE name = 'Home Goods')),
       ('Set of Kitchen Knives', 'Professional stainless steel knife set.', 65.00, 75, 'HOME-KNIVES-062',
        'http://example.com/kniveset.jpg', 'SharpCut', 4.7, TRUE,
        (SELECT id FROM categories WHERE name = 'Home Goods')),
       ('Decorative Wall Art', 'Modern abstract canvas wall art.', 55.00, 110, 'HOME-ART-063',
        'http://example.com/wallart.jpg', 'ArtisticHome', 4.3, TRUE,
        (SELECT id FROM categories WHERE name = 'Home Goods')),
       ('Smart Doorbell Camera', 'Video doorbell with motion detection.', 130.00, 60, 'HOME-DOOR-064',
        'http://example.com/doorbell.jpg', 'SecureEntry', 4.5, TRUE,
        (SELECT id FROM categories WHERE name = 'Home Goods')),
       ('Patio Bistro Set', 'Outdoor table and two chairs set.', 220.00, 30, 'HOME-PATIO-065',
        'http://example.com/patiodining.jpg', 'OutdoorLiving', 4.6, TRUE,
        (SELECT id FROM categories WHERE name = 'Home Goods')),
       ('Men''s Polo Shirt', 'Classic fit polo shirt with collar.', 30.00, 350, 'APP-POLO-066',
        'http://example.com/poloshirt.jpg', 'CasualStyle', 4.4, TRUE,
        (SELECT id FROM categories WHERE name = 'Apparel')),
       ('Women''s Maxi Dress', 'Flowy long maxi dress for casual wear.', 45.00, 200, 'APP-MAXI-067',
        'http://example.com/maxidress.jpg', 'SunnyWear', 4.7, TRUE, (SELECT id FROM categories WHERE name = 'Apparel')),
       ('Unisex Baseball Cap', 'Adjustable cotton baseball cap.', 18.00, 400, 'APP-CAP-068',
        'http://example.com/baseballcap.jpg', 'HeadWear', 4.0, TRUE,
        (SELECT id FROM categories WHERE name = 'Apparel')),
       ('Sneakers (High-Top)', 'Stylish high-top sneakers for everyday.', 70.00, 150, 'APP-SNEAK-069',
        'http://example.com/hightops.jpg', 'UrbanKicks', 4.5, TRUE, (SELECT id FROM categories WHERE name = 'Apparel')),
       ('Winter Scarf (Knitted)', 'Warm knitted scarf for cold weather.', 25.00, 280, 'APP-SCARF-070',
        'http://example.com/winterscarf.jpg', 'CozyWarmth', 4.6, TRUE,
        (SELECT id FROM categories WHERE name = 'Apparel')),
       ('Exercise Bike', 'Stationary exercise bike for home cardio.', 280.00, 40, 'SPORT-EBIKE-071',
        'http://example.com/exercisebike.jpg', 'CardioFit', 4.8, TRUE,
        (SELECT id FROM categories WHERE name = 'Sports & Outdoors')),
       ('Football (Official Size)', 'Durable football for training and games.', 25.00, 180, 'SPORT-FOOT-072',
        'http://example.com/football.jpg', 'GameTime', 4.5, TRUE,
        (SELECT id FROM categories WHERE name = 'Sports & Outdoors')),
       ('Camping Chair (Foldable)', 'Portable and comfortable folding camping chair.', 35.00, 160, 'SPORT-CCHAIR-073',
        'http://example.com/campingchair.jpg', 'RelaxOut', 4.2, TRUE,
        (SELECT id FROM categories WHERE name = 'Sports & Outdoors')),
       ('Swim Goggles', 'Anti-fog swim goggles with UV protection.', 15.00, 250, 'SPORT-SWIM-074',
        'http://example.com/swimgoggles.jpg', 'AquaVision', 4.3, TRUE,
        (SELECT id FROM categories WHERE name = 'Sports & Outdoors')),
       ('Jump Rope (Adjustable)', 'Speed jump rope with adjustable length.', 12.00, 300, 'SPORT-JUMP-075',
        'http://example.com/jumprope.jpg', 'CardioPro', 4.1, TRUE,
        (SELECT id FROM categories WHERE name = 'Sports & Outdoors')),
       ('Portable Charger 20000mAh', 'High-capacity power bank for mobile devices.', 40.00, 150, 'POWERB-076',
        'http://example.com/powerbank.jpg', 'ChargeFast', 4.7, TRUE,
        (SELECT id FROM categories WHERE name = 'Electronics')),
       ('Gaming Headset RGB', 'Over-ear gaming headset with surround sound.', 75.00, 80, 'GAMEHEAD-077',
        'http://example.com/gamingheadset.jpg', 'ApexSound', 4.6, TRUE,
        (SELECT id FROM categories WHERE name = 'Electronics')),
       ('Wireless Mouse Ergo', 'Ergonomic wireless mouse for comfort.', 25.00, 200, 'MOUSE-ERGO-078',
        'http://example.com/ergomouse.jpg', 'ComfortClick', 4.5, TRUE,
        (SELECT id FROM categories WHERE name = 'Electronics')),
       ('Webcam Full HD', '1080p webcam for video calls and streaming.', 35.00, 120, 'WEBCAM-079',
        'http://example.com/webcam.jpg', 'ClearView', 4.4, TRUE,
        (SELECT id FROM categories WHERE name = 'Electronics')),
       ('Smart Plug Mini (2-pack)', 'Wi-Fi enabled smart plugs for appliances.', 28.00, 180, 'SMARTPLUG-080',
        'http://example.com/smartplug.jpg', 'SmartLink', 4.2, TRUE,
        (SELECT id FROM categories WHERE name = 'Electronics')),
       ('The Hitchhiker''s Guide to the Galaxy', 'Sci-fi comedy novel by Douglas Adams.', 13.00, 380, 'BOOK-HHG-081',
        'http://example.com/hitchhiker.jpg', 'Ballantine Books', 4.7, TRUE,
        (SELECT id FROM categories WHERE name = 'Books')),
       ('Dune', 'Science fiction novel by Frank Herbert.', 16.00, 320, 'BOOK-DUNE-082', 'http://example.com/dune.jpg',
        'Ace Books', 4.8, TRUE, (SELECT id FROM categories WHERE name = 'Books')),
       ('The Hobbit', 'Fantasy novel by J.R.R. Tolkien.', 11.50, 480, 'BOOK-HOBBIT-083',
        'http://example.com/hobbit.jpg', 'Houghton Mifflin', 4.9, TRUE,
        (SELECT id FROM categories WHERE name = 'Books')),
       ('Where the Crawdads Sing', 'Novel by Delia Owens.', 15.00, 410, 'BOOK-CRWD-084',
        'http://example.com/crawdads.jpg', 'G.P. Putnam''s Sons', 4.6, TRUE,
        (SELECT id FROM categories WHERE name = 'Books')),
       ('Atomic Habits', 'Self-help book by James Clear.', 17.00, 500, 'BOOK-ATOMIC-085',
        'http://example.com/atomichabits.jpg', 'Avery', 4.9, TRUE, (SELECT id FROM categories WHERE name = 'Books')),
       ('Food Processor', 'Multi-functional food processor for kitchen tasks.', 105.00, 65, 'HOME-FOODP-086',
        'http://example.com/foodprocessor.jpg', 'KitchenAid', 4.7, TRUE,
        (SELECT id FROM categories WHERE name = 'Home Goods')),
       ('Bath Towel Set (4-piece)', 'Soft and absorbent cotton bath towel set.', 45.00, 130, 'HOME-TOWEL-087',
        'http://example.com/towelset.jpg', 'PlushHome', 4.4, TRUE,
        (SELECT id FROM categories WHERE name = 'Home Goods')),
       ('Desk Lamp LED', 'Modern LED desk lamp with adjustable brightness.', 30.00, 180, 'HOME-DLAMP-088',
        'http://example.com/desklamp.jpg', 'BrightIdeas', 4.3, TRUE,
        (SELECT id FROM categories WHERE name = 'Home Goods')),
       ('Decorative Throw Pillows (Set of 2)', 'Stylish throw pillows for couch or bed.', 35.00, 90, 'HOME-PILLOWS-089',
        'http://example.com/throwpillows.jpg', 'CozyDecor', 4.5, TRUE,
        (SELECT id FROM categories WHERE name = 'Home Goods')),
       ('Portable Garment Steamer', 'Handheld steamer for quick wrinkle removal.', 40.00, 110, 'HOME-STEAM-090',
        'http://example.com/garmentsteamer.jpg', 'SmoothClothes', 4.2, TRUE,
        (SELECT id FROM categories WHERE name = 'Home Goods')),
       ('Men''s Dress Shirt', 'Formal long-sleeve dress shirt.', 55.00, 150, 'APP-DSHIRT-091',
        'http://example.com/dressshirt.jpg', 'GentlemanStyle', 4.6, TRUE,
        (SELECT id FROM categories WHERE name = 'Apparel')),
       ('Women''s Cardigan Sweater', 'Soft knit cardigan for layering.', 40.00, 180, 'APP-CARD-092',
        'http://example.com/cardigan.jpg', 'LayerUp', 4.5, TRUE, (SELECT id FROM categories WHERE name = 'Apparel')),
       ('Kids'' Rain Boots', 'Waterproof rain boots for children.', 28.00, 200, 'APP-KIDSBOOT-093',
        'http://example.com/kidsrainboots.jpg', 'PuddleJumpers', 4.7, TRUE,
        (SELECT id FROM categories WHERE name = 'Apparel')),
       ('Sport Sunglasses', 'UV protected sport sunglasses.', 22.00, 250, 'APP-SUN-094',
        'http://example.com/sportsunglasses.jpg', 'EyeShield', 4.3, TRUE,
        (SELECT id FROM categories WHERE name = 'Apparel')),
       ('Running Belt with Pouch', 'Adjustable running belt for essentials.', 18.00, 300, 'SPORT-RUNBELT-095',
        'http://example.com/runningbelt.jpg', 'ActiveCarry', 4.1, TRUE,
        (SELECT id FROM categories WHERE name = 'Sports & Outdoors')),
       ('Yoga Blocks (Set of 2)', 'High-density foam yoga blocks for support.', 20.00, 150, 'SPORT-YBLOCK-096',
        'http://example.com/yogablocks.jpg', 'FlexFit', 4.4, TRUE,
        (SELECT id FROM categories WHERE name = 'Sports & Outdoors')),
       ('Resistance Loop Bands (Set of 3)', 'Loop bands for strength training and physical therapy.', 15.00, 280,
        'SPORT-RLOOP-097', 'http://example.com/loopbands.jpg', 'StrongBody', 4.5, TRUE,
        (SELECT id FROM categories WHERE name = 'Sports & Outdoors')),
       ('Portable Picnic Blanket', 'Waterproof and foldable picnic blanket.', 30.00, 120, 'SPORT-PICNIC-098',
        'http://example.com/picnicblanket.jpg', 'OutdoorJoy', 4.6, TRUE,
        (SELECT id FROM categories WHERE name = 'Sports & Outdoors')),
       ('Adjustable Inline Skates', 'Inline skates with adjustable sizing for kids.', 70.00, 50, 'SPORT-SKATES-099',
        'http://example.com/inlineskates.jpg', 'SpeedRoll', 4.7, TRUE,
        (SELECT id FROM categories WHERE name = 'Sports & Outdoors')),
       ('Electric Scooter for Adults', 'Foldable electric scooter with long range.', 400.00, 20, 'SPORT-ESCOOT-100',
        'http://example.com/escooter.jpg', 'UrbanGlide', 4.8, TRUE,
        (SELECT id FROM categories WHERE name = 'Sports & Outdoors'));
