spring:
  datasource:
    url: jdbc:postgresql://localhost:15433/books
    username: books_user
    password: books_password
  jpa:
    hibernate:
      ddl-auto: update
  test:
    database:
      replace: none